// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Request.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	RequestType          int32    `protobuf:"varint,1,opt,name=requestType,proto3" json:"requestType,omitempty"`
	Key                  int32    `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	Val                  int32    `protobuf:"varint,3,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac56d74daff02b5a, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRequestType() int32 {
	if m != nil {
		return m.RequestType
	}
	return 0
}

func (m *Request) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Request) GetVal() int32 {
	if m != nil {
		return m.Val
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "main.request")
}

func init() { proto.RegisterFile("Request.proto", fileDescriptor_ac56d74daff02b5a) }

var fileDescriptor_ac56d74daff02b5a = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x0d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53,
	0xf2, 0xe7, 0x62, 0x2f, 0x82, 0x08, 0x0b, 0x29, 0x70, 0x71, 0x43, 0x99, 0x21, 0x95, 0x05, 0xa9,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0xc8, 0x42, 0x42, 0x02, 0x5c, 0xcc, 0xd9, 0xa9, 0x95,
	0x12, 0x4c, 0x60, 0x19, 0x10, 0x13, 0x24, 0x52, 0x96, 0x98, 0x23, 0xc1, 0x0c, 0x11, 0x01, 0x32,
	0x93, 0xd8, 0xc0, 0xa6, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x99, 0x64, 0xde, 0xf3, 0x6e,
	0x00, 0x00, 0x00,
}
