// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Response.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Key                  int32    `protobuf:"varint,3,opt,name=key,proto3" json:"key,omitempty"`
	Val                  int32    `protobuf:"varint,4,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c4c7055b2f7bc3f, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Response) GetVal() int32 {
	if m != nil {
		return m.Val
	}
	return 0
}

func init() {
	proto.RegisterType((*Response)(nil), "main.Response")
}

func init() { proto.RegisterFile("Response.proto", fileDescriptor_2c4c7055b2f7bc3f) }

var fileDescriptor_2c4c7055b2f7bc3f = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x0b, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc,
	0x53, 0x8a, 0xe2, 0xe2, 0x80, 0x89, 0x0b, 0x49, 0x70, 0xb1, 0x17, 0x97, 0x26, 0x27, 0xa7, 0x16,
	0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x04, 0xc1, 0xb8, 0x42, 0x02, 0x5c, 0xcc, 0xb9, 0xc5,
	0xe9, 0x12, 0x4c, 0x40, 0x51, 0xce, 0x20, 0x10, 0x13, 0x24, 0x92, 0x9d, 0x5a, 0x29, 0xc1, 0x0c,
	0x14, 0x61, 0x0d, 0x02, 0x31, 0x41, 0x22, 0x65, 0x89, 0x39, 0x12, 0x2c, 0x10, 0x11, 0x20, 0x33,
	0x89, 0x0d, 0x6c, 0x91, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x69, 0xe0, 0xa6, 0x7a, 0x00,
	0x00, 0x00,
}
